export const DFORM_FILE_NAME = {
  AddressPicker: 'AddressPicker',
  CoverRadio: 'CoverRadio',
  ExtraInput: 'ExtraInput',
  MultiplePicker: 'MultiplePicker',
  DformInput: 'NomarInput',
  DformSelect: 'NomarSelect',
  DformPicker: 'NomarPicker',
  DformSwitch: 'NomarSwitch',
  DformTextArea: 'NomarTextArea',
  DformDatePicker: 'NomarDatePicker',
  DformRadio: 'NomarRadio',
  DformCheckBox: 'NomarCheckBox',
  DformImagePicker: 'NomarImagePicker',
  DformCustom: 'NomarCustom',
  DformText: 'NomarText',
  DformFile: 'NomarFile',
  RangeDatePicker: 'RangeDatePicker',
};
