export const DFORM_FILE_NAME = {
  AddressPicker: 'AddressPicker',
  CoverRadio: 'CoverRadio',
  ExtraInput: 'ExtraInput',
  MultiplePicker: 'MultiplePicker',
  NomarInput: 'DformInput',
  NomarSelect: 'DformSelect',
  NomarPicker: 'DformPicker',
  NomarSwitch: 'DformSwitch',
  NomarTextArea: 'DformTextArea',
  NomarDatePicker: 'DformDatePicker',
  NomarRadio: 'DformRadio',
  NomarCheckBox: 'DformCheckBox',
  NomarImagePicker: 'DformImagePicker',
  // NomarCustom: 'DformCustom',
  NomarText: 'DformText',
  // NomarFile: 'DformFile',
  RangeDatePicker: 'RangeDatePicker',
};
